"""
generateData.py is the source code for creating fake data for the relations.
The random data is generated by the package of random.

"""

import linecache
import random
import decimal
from random import randint
from datetime import date

#for the generation of random string type data
alphabet = 'abcdefghijklmnopqrstuvwxyz'
min = 3
max = 10

"""
Generate data for university(university_id, university_name)
The data is saved in file university.txt
"""
total = 11
string = ''
FILE = open("university.txt", "w")
for count in xrange(1, total):
	for x in random.sample(alphabet, random.randint(min,max)):
		string+=x
	FILE.write(str(count)+'	'+string+'\n')
	string=''
FILE.close()

"""
Generate data for player(player_id, player_name)
The data is saved in file player.txt
"""
total = 101
string = ''
FILE = open("player.txt", "w")
for count in xrange(1, total):
	for x in random.sample(alphabet, random.randint(min,max)):
		string+=x
	FILE.write(str(count)+'	'+string+'\n')
	string=''
FILE.close()

"""
Generate data for coach(coach_id, coach_name, coach_address_id)
The data is saved in file coach.txt
"""
total = 11
string = ''
FILE = open("coach.txt", "w")
for count in xrange(1, total):
	for x in random.sample(alphabet, random.randint(min,max)):
		string+=x
	num = random.randint(1, 200)
	FILE.write(str(count)+'	'+string+'	'+str(num)+'\n')
	string=''
FILE.close()

"""
Generate data for player_for(player_id, university_id)
The data is saved in file player_for.txt
"""
total = 101
FILE = open("player_for.txt", "w")
for count in xrange(1, total):
	num = random.randint(1, 10)
	FILE.write(str(count)+'	'+str(num)+'\n')
FILE.close()

"""
Generate data for work_for(coach_id, university_id)
The data is saved in file work_for.txt
"""
total = 11
FILE = open("work_for.txt", "w")
for count in xrange(1, total):
	num = random.randint(1, 10)
	FILE.write(str(count)+'	'+str(num)+'\n')
FILE.close()

"""
Generate data for locate(university_id, address_id)
The data is saved in file locate.txt
"""
total = 11
FILE = open("locate.txt", "w")
for count in xrange(1, total):
	num = random.randint(1, 200)
	FILE.write(str(count)+'	'+str(num)+'\n')
FILE.close()

"""
Generate data for live_at(player_id, address_id)
The data is saved in file live_at.txt
"""
total = 101
FILE = open("live_at.txt", "w")
for count in xrange(1, total):
	num = random.randint(1, 200)
	FILE.write(str(count)+'	'+str(num)+'\n')
FILE.close()

"""
Generate data for address(address_id, number, street, city, state, zip)
The data is saved in file address.txt
"""
total = 201
street = ''
city = ''
state = ''
FILE = open("address.txt", "w")
for count in xrange(1, total):
	num = random.randint(1, 10000)
	for x in random.sample(alphabet, random.randint(min,max)):
		street+=x
	for x in random.sample(alphabet, random.randint(2,max)):
		city+=x
	for x in random.sample(alphabet, random.randint(2,5)):
		state+=x
	zip = random.randint(1, 100000)
	FILE.write(str(count)+'	'+str(num)+'	'+street+'	'+city+'	'+state+'	'+str(zip)+'\n')
	street=''
	city=''
	state=''
FILE.close()

"""
Generate data for game(game_id, game_date, game_result, home_id, guest_id)
The data is saved in file game.txt
"""
FILE = open("game.txt", "w")
for count in xrange(1, 101):
	year = random.choice(range(2000, 2014))
	month = random.choice(range(1, 12))
	day = random.choice(range(1, 28))
	randomdate = date(year, month, day)
	while True:
		home_id = random.randint(1, 10)
		guest_id = random.randint(1, 10)
		if home_id != guest_id:
			break;
	result = random.choice(range(1, 2))
	if result == 1:
		game_result = home_id
	else:
		game_result = guest_id
	FILE.write(str(count)+'	'+str(randomdate)+'	'+str(game_result)+'	'+str(home_id)+'	'+str(guest_id)+'\n')
FILE.close()

"""
Generate data for hold_at(game_id, address_id)
The data is saved in file hold_at.txt
"""
FILE = open("hold_at.txt", "w")
for count in xrange(1, 101):
	address_id = random.randint(1, 200)
	FILE.write(str(count)+'	'+str(address_id)+'\n')
FILE.close()



